name: Java CI with Maven, and running tests without NonDex and with NonDex


on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean install -DskipTests -pl 2.x/chapter2-1 -am
      - name: Run tests WITHOUT NonDex tool
        run: mvn -pl 2.x/chapter2-1 test -Dtest=com.didispace.chapter21.Chapter21ApplicationTests#testUserController
      - name: Run tests WITH NonDex tool
        run: mvn -pl 2.x/chapter2-1 test edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=com.didispace.chapter21.Chapter21ApplicationTests#testUserController -DnondexRuns=10
